name: mtdgame
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - ld_impl_linux-64=2.40
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libnsl=2.0.0
  - libsqlite=3.40.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - ncurses=6.3
  - openssl=3.1.0
  - pip=23.1
  - python=3.9.13
  - readline=8.2
  - setuptools=67.6.1
  - sqlite=3.40.0
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.40.0
  - xz=5.2.6
  - pip:
      - adal==1.2.7
      - argon2-cffi==20.1.0
      - asgiref==3.6.0
      - async-generator==1.10
      - async-timeout==4.0.2
      - attrs==20.3.0
      - azure-batch==11.0.0
      - azure-common==1.1.27
      - azure-core==1.18.0
      - azure-identity==1.6.1
      - azure-storage-blob==12.9.0
      - backcall==0.2.0
      - bleach==3.3.0
      - certifi==2020.12.5
      - cffi==1.14.5
      - channels==4.0.0
      - channels-redis==4.1.0
      - chardet==4.0.0
      - cryptography==3.4.8
      - cycler==0.10.0
      - decorator==4.4.2
      - defusedxml==0.7.1
      - django==3.2.10
      - django-cors-headers==3.14.0
      - django-debug-toolbar==4.0.0
      - djangorestframework==3.14.0
      - djangorestframework-simplejwt==5.2.2
      - entrypoints==0.3
      - idna==2.10
      - ipykernel==5.5.3
      - ipython==7.23.0
      - ipython-genutils==0.2.0
      - ipywidgets==7.6.3
      - isodate==0.6.0
      - jedi==0.18.0
      - jinja2==2.11.3
      - joblib==1.2.0
      - jsonschema==3.2.0
      - jupyter==1.0.0
      - jupyter-client==6.1.12
      - jupyter-console==6.4.0
      - jupyter-core==4.7.1
      - jupyterlab-pygments==0.1.2
      - jupyterlab-widgets==1.0.0
      - kiwisolver==1.3.1
      - markupsafe==1.1.1
      - matplotlib==3.4.1
      - matplotlib-inline==0.1.2
      - mistune==0.8.4
      - msal==1.14.0
      - msal-extensions==0.3.0
      - msgpack==1.0.5
      - msrest==0.6.21
      - msrestazure==0.6.4
      - nbclient==0.5.3
      - nbconvert==6.0.7
      - nbformat==5.1.3
      - nest-asyncio==1.5.1
      - networkx==2.5.1
      - notebook==6.4.1
      - numpy==1.20.2
      - oauthlib==3.1.1
      - packaging==20.9
      - pandas==1.2.4
      - pandocfilters==1.4.3
      - parso==0.8.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==8.3.2
      - plotly==5.10.0
      - portalocker==1.7.1
      - prometheus-client==0.10.1
      - prompt-toolkit==3.0.18
      - ptyprocess==0.7.0
      - pulp==2.7.0
      - pycparser==2.20
      - pygments==2.9.0
      - pyjwt==2.1.0
      - pyparsing==2.4.7
      - pyrsistent==0.17.3
      - python-dateutil==2.8.1
      - pytz==2021.1
      - pyzmq==22.0.3
      - qtconsole==5.1.0
      - qtpy==1.9.0
      - redis==4.5.4
      - requests==2.25.1
      - requests-oauthlib==1.3.0
      - scipy==1.6.3
      - seaborn==0.12.0
      - send2trash==1.5.0
      - simpy==4.0.1
      - six==1.15.0
      - sqlparse==0.4.3
      - tenacity==8.2.2
      - terminado==0.9.4
      - testpath==0.4.4
      - tornado==6.1
      - traitlets==5.0.5
      - urllib3==1.26.5
      - wcwidth==0.2.5
      - webencodings==0.5.1
      - widgetsnbextension==3.5.1
